[package]
name = "alternate_screen_wrapper"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = { version = "0.28.1", default-features = false, optional = true }

[features]
crossterm = ["dep:crossterm"]
