[package]
name = "alternate_screen_wrapper"
description = "enter end leave alternate screen in one line"
license = "MIT"
version = "0.1.1"
edition = "2021"

[dependencies]
crossterm = { version = "0.28.1", optional = true }

[features]
crossterm = ["dep:crossterm"]
